version: "3.9"

services:
  nginx_server:
    container_name: nginx_container
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8070:87
    depends_on:
      - application
    networks:
      - global_jobs_app_network

  application:
    container_name: application_container
    build: ./project/.
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "-f", "http://localhost:8000"]
      retries: 5
      timeout: 10s
      interval: 10s
    platform: linux/amd64
    networks:
      - global_jobs_app_network
    depends_on:
      - database
      - graphql

  database:
    container_name: database_container
    image: postgres:latest
    environment:
      POSTGRES_DB: jobs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kirill
    ports:
      - 5436:5436
    networks:
      - global_jobs_app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck/"]

  graphql:
    container_name: graphql_container
    image: graphile/postgraphile
    networks:
      - global_jobs_app_network
    depends_on:
      - database

networks:
  global_jobs_app_network:
    external: false
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: bridge
      config:
        gateway: 192.253.27.01/25
        subnet: 19.23.25.01/20

    name: global_jods_app_network
    internal: true

