version: "3.9"

services:
  nginx_server:
    container_name: nginx_container
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8070:87
    depends_on:
      - application
    networks:
      - global_jobs_app_network

  application:
    container_name: application_container
    build: ./project/.
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "-f", "http://localhost:8000"]
      retries: 5
      timeout: 10s
      interval: 10s
    env_file: ./project/env_file.env
    platform: linux/amd64
    networks:
      - global_jobs_app_network
    depends_on:
      - database
      - graphql

  database:
    container_name: database_container
    image: postgres:latest
    environment:
      POSTGRES_DB: jobs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kirill
    ports:
      - 5436:5436
    networks:
      - global_jobs_app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck/"]

  graphql:
    container_name: graphql_container
    image: graphile/postgraphile
    networks:
      - global_jobs_app_network
    environment:
      - DATABASE_URL=postgresql://postgres:Kirill@database:5436/jobs_db
    depends_on:
      - database
    healthcheck:
      test: ["CMD"]
      retries: 5
      interval: 10s
      timeout: 10s
    ports:
      - 5000:5000

networks:
  global_jobs_app_network:
    external: false
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.1/20
          gateway: 172.28.0.2

    name: global_jods_app_network
    internal: true

