version: "3.9"

services:

  nginx_server:
    container_name: nginx_container
    ports:
      - target: 80
      - published: 8002
      - mode: host
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - 'node.labels.TAG==jobs_resume_service'
      mode: replicated
      replicas: 1
    depends_on:
      - application

  application:
    container_name: application_server
    image: crazycoderrr/jobs_resume_service_app
    ports:
      - published: 8000
      - target: 8000
      - mode: host
    env_file: ./proj_env.env
    deploy:
      placement:
        constraints:
          - 'node.labels.TAG==jobs_resume_service'
      update_config:
        failure_action: rollback
        delay: 10s
        parallelism: 1
      mode: global
    healthcheck:
      timeout: 10s
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck/"]
      interval: 10s
      retries: 5
    depends_on:
      - database

  database:
    container_name: postgresql_database
    image: postgres:latest
    environment:
      POSTGRES_DB: jobs_db
      POSTGRES_USER: jobs_user
      POSTGRES_PASSWORD: Kirill
    healthcheck:
      test: ["CMD", "pg_isready", "jobs_db"]
      retries: 5
      interval: 10s
      timeout: 10s
    ports:
      - target: 5437
      - published: 5437
      - mode: host
    deploy:
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      mode: replicated
      placement:
        constraints:
          - "node.labels.TAG==jobs_resume_service"
      replicas: 1

  graphql:
    container_name: graphql_container
    image: graphile/postgraphile
    environment:
      DATABASE_URL: postgres://jobs_user:Kirill@localhost:5437/jobs_db
    command: ["postgraphile", "--connection", "$DATABASE_URL", "--host",
    "0.0.0.0", "--port", "5001", "--schema", "public"]
    ports:
      - target: 5001
      - published: 5001
      - mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck/"]
      retries: 5
      timeout: 10s
      interval: 10s
    deploy:
      replicas: 1
      mode: replicated
      update_config:
        failure_action: rollback
        delay: 10s
        parallelism: 1
      placement:
        constraints:
          - "node.labels.TAG==jobs_resume_service"

networks:
  jobs_project_network:
    external: true
    name: jobs_project_network