version: "3.9"

services:

  database:
    container_name: postgresql_db
    image: postgres:latest
    environment:
      POSTGRES_DB: graphql_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kirill
    volumes:
      - ./init:/etc/docker-entrypoint-init.d/
    ports:
      - 5435:5435

  graphql:
    container_name: graphql
    image: graphile/postgraphile
    links:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:Kirill@localhost:5434/graphql_db
    expose:
      - 5001
    command: ["postgraphile", "--connection", "postgres://postgres:Kirill@localhost:5434/graphql_db", "--schema", "default_schema", "--host", "0.0.0.0",  "--port", "5001"]
    depends_on:
      - database
    ports:
      - 5001:5001




